import { describe, expect, it } from "vitest";
import {
  aadhaarChecks,
  dlChecks,
  icaoCheckDigit,
  icaoValid,
  passportChecks,
  verhoeffValid,
  visaChecks,
} from "./checksum";

// These are not made-up strings. Each was generated by independently running
// the same Verhoeff / ICAO 9303 arithmetic in a throwaway script and picking
// the check digit that makes it valid, so the test is verifying the
// implementation against the algorithm's own math, not against itself.

describe("verhoeffValid", () => {
  it("accepts a genuinely valid Aadhaar-shaped number", () => {
    expect(verhoeffValid("234567890124")).toBe(true);
    expect(verhoeffValid("912345678905")).toBe(true);
  });

  it("rejects the same number with the last digit altered", () => {
    // This is the exact scenario that matters: a forger changes one digit.
    for (let d = 0; d <= 9; d += 1) {
      const candidate = "23456789012" + d;
      if (candidate === "234567890124") continue;
      expect(verhoeffValid(candidate)).toBe(false);
    }
  });

  it("rejects a single transposed digit (Verhoeff's whole purpose)", () => {
    // 234567890124 with positions 2 and 3 swapped.
    expect(verhoeffValid("243567890124")).toBe(false);
  });

  it("rejects non-numeric input instead of throwing", () => {
    expect(verhoeffValid("23456789012A")).toBe(false);
    expect(verhoeffValid("")).toBe(false);
  });
});

describe("icaoCheckDigit / icaoValid", () => {
  it("matches a hand-verified MRZ field", () => {
    // '<' filler = 0, digits = value, letters = charCode-55, weights 7-3-1 cyclic.
    expect(icaoCheckDigit("900115")).toBe(8);
    expect(icaoValid("900115", "8")).toBe(true);
  });

  it("rejects a wrong check digit", () => {
    expect(icaoValid("900115", "7")).toBe(false);
  });

  it("rejects a non-digit check digit input instead of throwing", () => {
    expect(icaoValid("900115", "X")).toBe(false);
  });
});

describe("aadhaarChecks", () => {
  it("passes all three checks for a genuinely valid number", () => {
    const checks = aadhaarChecks({ aadhaar_number: "2345 6789 0124" });
    expect(checks.every((c) => c.passed === true)).toBe(true);
  });

  it("fails the Verhoeff check when the last digit is altered", () => {
    const checks = aadhaarChecks({ aadhaar_number: "2345 6789 0121" });
    const verhoeff = checks.find((c) => c.check === "aadhaar_verhoeff");
    expect(verhoeff?.passed).toBe(false);
  });

  it("flags a leading 0 or 1 as never-issued, not a silent pass", () => {
    const checks = aadhaarChecks({ aadhaar_number: "012345678905" });
    const leading = checks.find((c) => c.check === "aadhaar_leading_digit");
    expect(leading?.passed).toBe(false);
  });

  it("returns passed:null (not false, not a throw) when nothing was read", () => {
    const checks = aadhaarChecks({});
    expect(checks).toHaveLength(1);
    expect(checks[0]?.passed).toBeNull();
  });

  it("never throws on garbage input", () => {
    expect(() => aadhaarChecks({ aadhaar_number: "not a number at all" })).not.toThrow();
    expect(() => aadhaarChecks({ aadhaar_number: "🙂🙂🙂" })).not.toThrow();
  });
});

describe("passportChecks", () => {
  const validLine2 = "M1234567<0IND9001158M3012316<<<<<<<<<<<<<<08";

  it("passes every check digit on a genuinely valid MRZ line", () => {
    const checks = passportChecks({ mrz_line2: validLine2 });
    const critical = checks.filter((c) =>
      [
        "passport_number_cd",
        "passport_dob_cd",
        "passport_expiry_cd",
        "passport_composite_cd",
      ].includes(c.check),
    );
    expect(critical.every((c) => c.passed === true)).toBe(true);
  });

  it("flags a single altered digit via both its own check digit and the composite", () => {
    // Flip one digit inside the DOB field (position 14, '0'->'9') without
    // touching any check digit - this is exactly what a forger who doesn't
    // know the composite algorithm exists would do.
    const tampered = validLine2.slice(0, 14) + "9" + validLine2.slice(15);
    const checks = passportChecks({ mrz_line2: tampered });
    const dobCheck = checks.find((c) => c.check === "passport_dob_cd");
    const composite = checks.find((c) => c.check === "passport_composite_cd");
    expect(dobCheck?.passed).toBe(false);
    expect(composite?.passed).toBe(false);
  });

  it("returns passed:null when the MRZ was not readable, instead of a false failure", () => {
    const checks = passportChecks({ mrz_line2: "" });
    expect(checks[0]?.passed).toBeNull();
  });

  it("flags an expired passport via the validity window check", () => {
    // Build a line with a past expiry (2001) but keep its own check digit
    // internally consistent so only the window check fires.
    const expiry = "011231";
    const cd = icaoCheckDigit(expiry);
    const expired = validLine2.slice(0, 21) + expiry + String(cd) + validLine2.slice(28);
    const checks = passportChecks({ mrz_line2: expired });
    const window = checks.find((c) => c.check === "passport_expiry_window");
    expect(window?.passed).toBe(false);
  });
});

describe("visaChecks", () => {
  it("returns passed:null when unreadable, never throws", () => {
    expect(() => visaChecks({})).not.toThrow();
    expect(visaChecks({})[0]?.passed).toBeNull();
  });
});

describe("dlChecks", () => {
  it("passes a well-formed national-grammar licence number", () => {
    const checks = dlChecks({ dl_number: "MH02 2015 1234567" });
    const format = checks.find((c) => c.check === "dl_format");
    const state = checks.find((c) => c.check === "dl_state_code");
    expect(format?.passed).toBe(true);
    expect(state?.passed).toBe(true);
  });

  it("rejects an unrecognised state code instead of silently passing", () => {
    const checks = dlChecks({ dl_number: "ZZ02 2015 1234567" });
    const state = checks.find((c) => c.check === "dl_state_code");
    expect(state?.passed).toBe(false);
  });

  it("never throws on an empty or garbage reading", () => {
    expect(() => dlChecks({})).not.toThrow();
    expect(() => dlChecks({ dl_number: "###" })).not.toThrow();
  });
});
